version: '3'

services:
  mauticdb:
    image: percona/percona-server:5.7
    container_name: mauticdb
    volumes:
      - ./mautic/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MAUTIC_DB_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  mautic:
    image: mautic/mautic:v4
    container_name: mautic
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
    ports:
      - ${MAUTIC_PORT}:80
    volumes:
      - ./mautic/mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=${MAUTIC_DB_USER}
      - MAUTIC_DB_PASSWORD=${MAUTIC_DB_PASSWORD}
      - MAUTIC_DB_NAME=${MAUTIC_DB_NAME}
      - MAUTIC_RUN_CRON_JOBS=true
      # - MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0